Repository oceanprotocol/pleuston, pull requests merged in 2018-09, with the labels that each got.

#52 Feature/docker automate
  .dockerignore
  Dockerfile
  README.md
  scripts/docker-entrypoint.sh
  src/config.js.template
Labels: status:wip

#113 Wait for flag from keeper-contracts when contracts are ready
  scripts/docker-entrypoint.sh
Labels: devops, enhancement

#120 New variable to enable waiting for contracts
  scripts/docker-entrypoint.sh
Labels: bug, devops
